Thermal conductivity models
UM-PEPL/HallThruster.jl pull request #120
Opened 2024-02-21 20:46 UTC by DecBrick

Add in Mitchner and Braginskii thermal conductivity models as a default along with the option for user-specified models. Updated relevant documentation

2024-02-21 20:56 UTC, archermarx reviewed
Looks ok, but need some changes. Aside from some typographical things I point out in individual comments, there are a few larger ones:

1. Have you tested this on actual simulations? Something looks off with the way this interfaces with the implicit solver. 

2. Can you compare the performance of this new version to an identical simulation on the previous version?

3. Can you write tests for this new module?

4. With this capability, the if-else switch in the electron energy solve should be redundant. It would be best to just implement a LANDMARK model

5. Once the above has been done, the tutorial Jupyter notebook will need to be updated and verified to have similar behavior to before

2024-02-21 20:56 UTC, archermarx commented on docs/src/electron_thermal_conductivity.md
> +This form of the thermal conducitivity follows the result of S. I. Braginskii, inReviews of Plasma Physics, edited byM. A. Leontovich (Consultants Bureau, New York, 1965), Vol. 1,p. 205.:
*conductivity, also fix spaces in citation

2024-02-21 20:56 UTC, archermarx commented on docs/src/electron_thermal_conductivity.md
> +Where C is a constant that is based on the value of the effective charge for multiple charge states and Table 1 of the Braginskii reference. A `Braginski` model can be initialized in the user-defined
Braginskii (two 'i's)

2024-02-21 20:56 UTC, archermarx commented on docs/src/electron_thermal_conductivity.md
> +    B = params.cahce.B
params.cache (misspelling)

2024-02-21 20:56 UTC, archermarx commented on docs/src/electron_thermal_conductivity.md
> +    Te = params.cahce.Tev
same misspelling here

2024-02-21 20:56 UTC, archermarx commented on docs/src/electron_thermal_conductivity.md
> +
eliminate some unnecessary newlines

2024-02-21 20:56 UTC, archermarx commented on src/physics/thermal_conductivity.jl
> +S. I. Braginskii, inReviews of Plasma Physics, edited byM. A. Leontovich (Consultants Bureau, New York, 1965), Vol. 1,p. 205.
fix spaces in citation

2024-02-21 20:56 UTC, archermarx commented on src/physics/thermal_conductivity.jl
> +
remove some unnecessary newlines here

2024-02-21 20:56 UTC, archermarx commented on src/physics/thermal_conductivity.jl
> +    Mitchner, uses closure from M. Mitchner and C. H. Kruger, Jr.,Partially Ionized Gases(John Wiley andSons, Inc., New York, 1973). Pg. 94
fix spaces in citation and remove unnecessary newlines in function definition

2024-02-21 20:56 UTC, archermarx commented on src/simulation/electronenergy.jl
> -            #get adjusted coeffient for higher charge states
you should remove this whole if-else chain and just add a LANDMARK thermal conductivity model. i think it works out to be pretty close to the braginskii value

2024-02-21 20:56 UTC, archermarx commented on src/simulation/electronenergy.jl
> +            κ0 = κ[i]
note that here kL, k0, and kR are actually kL/Te, k0/Te, and kR/Te because of the implicit solver. that means that this probably won't work, unless i'm missing something

2024-02-21 21:06 UTC, DecBrick commented on src/simulation/electronenergy.jl
> +            κ0 = κ[i]
the nϵ term should be equivalent to 3/2 * neTe so by comparing this form to that of Mitchner, I think the old forms are the correct kappa values, not kappa/Te. The implementation works out similarly with both the Mitchner and Braginskii models

2024-02-21 21:24 UTC, archermarx requested changes

2024-02-21 21:24 UTC, archermarx commented on src/physics/thermal_conductivity.jl
> +
don't need all these spaces still

2024-02-21 21:24 UTC, archermarx commented on src/physics/thermal_conductivity.jl
> +
should return kappa

2024-02-21 21:26 UTC, DecBrick commented on src/physics/thermal_conductivity.jl
> +
You're right, the interesting bit is that it ran in this buggy version.

2024-02-21 21:30 UTC, archermarx commented on src/simulation/electronenergy.jl
> +            κ0 = κ[i]
oh, nvm you're right! brain fart on my part

2024-02-21 21:31 UTC, archermarx requested changes

2024-02-21 21:31 UTC, archermarx commented on src/physics/thermal_conductivity.jl
> +struct LANDMARK_kappa <: ThermalConductivityModel end
call it LANDMARK_conductivity or similar

2024-02-21 21:54 UTC, archermarx commented
Tests are broken. You'll need to fix them and add some new ones for the new functionality

2024-02-22 18:36 UTC, DecBrick commented
To the performance point. Using the example simulation with 300 cells, dt of 5ns, runtime of 1ms, and save 500, the old version takes 81.93s to evaluate while this version takes 81.53s to evaluate

2024-02-22 18:55 UTC, archermarx approved these changes
Looks good! Thank you!

2024-02-22 18:56 UTC, merged

2024-02-22 19:22 UTC, archermarx commented
Addressed [ @117](https://github.com/UM-PEPL/HallThruster.jl/issues/117#issue-2139408101)